### PR TITLE
Support AWSCredentialsProvider override

### PR DESCRIPTION
**Pull request by margussipria**
Added `S3CredentialsProvider` SettingKey, default credentials can be overridden with custom implementation:

```scala
S3credentialsProvider := { (bucket: String) =>
  new ProfileCredentialsProvider("maven-publisher")
}
```

```scala
// With signature 
SettingKey[String => AWSCredentialsProvider]
// There can be still be providers that give credentials based on bucked names
```

Later if `makePropertiesFileCredentialsProvider` would be public, one can use that specific resolver without needing whole chain, even change file name.

Also reverted `getRegionNameFromService`, now building second client for fetching bucket location, if previous steps failed, if not client would not be build.

### CODE REVIEW

**Comment by margussipria** [comment]
Noticed that I had correct region value in my ` ~/.aws/config` and thats why region location fetching was working, so I opened https://github.com/aws/aws-sdk-java/issues/1142

**Comment by tpunder** [comment]
@margussipria Thanks!  Give me some time to review and get this merged in.

**Comment by marjohr** [comment]
This would be much appreciated if it was fixed and merged.

**Comment by nandotorterolo** [comment]
@tpunder Appreciated merging this pr.

**Comment by tpunder** [comment]
FYI this functionality was already merged and published.  There were some additional refactoring/style changes that have not been merged.

**Comment by tpunder** [comment]
I'm going to close this.  The "AWSCredentialsProvider override" part has been merged and is now documented in the README.md file:  https://github.com/frugalmechanic/fm-sbt-s3-resolver#custom-s3-credentials

I'm going to punt the rest of the style changes that are a part of this pull request for now.

**Pull request closed without merging**
